# Generated by Django 3.2.7 on 2022-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='photo',
            field=models.ImageField(default='image', upload_to='goods'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cost',
            field=models.CharField(default='cost', max_length=30),
        ),
    ]
