# Generated by Django 3.2.7 on 2022-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20220307_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cost',
            field=models.CharField(default='30', max_length=30),
        ),
    ]
