# Generated by Django 3.2.7 on 2022-03-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_goods_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.ImageField(upload_to='mainApp/images'),
        ),
    ]
