# Generated by Django 3.2.7 on 2022-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_goods_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
