# Generated by Django 3.2.7 on 2022-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_goods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='avaliable',
            field=models.BooleanField(default=True, verbose_name='avaliable'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='cost'),
        ),
    ]
